# AdamW Optimiser

In [24]:
import numpy as np
from tqdm import tqdm

def gradient(w):
    return np.array([1000 * w[0], 0.0001 * w[1]])

lr = 0.0015
beta1, beta2, eps = 0.9, 0.999, 1e-5

w_adam = [1.0, 1.0]
w_sgd = [1.0, 1.0]

m = np.zeros(2)
v = np.zeros(2)

for step in tqdm(range(1, 600)):

    g = gradient(w_adam)

    m = beta1 * m + (1 - beta1) * g
    v = beta2 * v + (1 - beta2) * g**2

    m_hat = m / (1 - beta1**step)
    v_hat = v / (1 - beta2**step)

    w_adam = w_adam - lr * m_hat / (np.sqrt(v_hat)+eps)
    w_sgd = w_sgd - lr * gradient(w_sgd)

    if step in [1, 5, 10, 50, 100, 150, 200, 300,400, 500]:
        print("-========")
        print(f"AdamW {np.around(w_adam, 5)}")

        print(f"SGD {np.round(w_sgd, 5)}")
        print("=========")

100%|██████████| 599/599 [00:00<00:00, 113528.61it/s]

-========
AdamW [0.9985  0.99864]
SGD [-0.5  1. ]
-========
AdamW [0.9925  0.99318]
SGD [-0.03125  1.     ]
-========
AdamW [0.98501 0.98637]
SGD [9.8e-04 1.0e+00]
-========
AdamW [0.92569 0.93249]
SGD [0.      0.99999]
-========
AdamW [0.85398 0.86733]
SGD [0.      0.99999]
-========
AdamW [0.78525 0.80478]
SGD [0.      0.99998]
-========
AdamW [0.71955 0.74488]
SGD [0.      0.99997]
-========
AdamW [0.59747 0.6331 ]
SGD [0.      0.99996]
-========
AdamW [0.48814 0.53207]
SGD [0.      0.99994]
-========
AdamW [0.39175 0.44179]
SGD [0.      0.99993]


In [ ]:
g = 2

prev_m = 0.4
prev_v = 0.016

m = 0.9 * 0.4 + 0.1 * 2
v = 0.999 * 0.016 + 0.001 * 4

m = 0.56
v = 0.019984

m_hat = 0.56 / (1 - 0.9**2) # step 2
v_hat = 0.019984 / (1 - 0.999**2) # step 2

m_hat = 2.94
v_hat = 9.99699

step = lr * 2.94 / np.sqrt(9.99699)
step = lr * 0.9298495849842916



In [ ]:
g = 4


m = 0
v = 0

m = 0.9 * 0 + 0.1 * 4
v = 0.999 * 0 + 0.001 * 16

m = 0.4
v = 0.016


# m_hat = 0.4 / (1 - 0.9**1)
# m_hat = 4
#
# v_hat = 0.016 / (1 - 0.999**1)
# v_hat = 16

# w_sgd = lr * 4 / np.sqrt(16)
# w_sgd = lr * 4 / 4

# w_sgd = 1.0 * lr -> STEP 1
#
# w_sgd = lr * 0.4 / np.sqrt(0.016)
# w_sgd = 3.16227766 * lr  -> STEP 1

w_sgd = 1.0 * lr

# MLP From Scratch

In [29]:
import numpy as np

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

weights = np.array([1.0, 0.0])
inputs = np.array([0.5, -0.3])
bias = 0.1
lr = 0.5
target = 1.0

prediction = sigmoid(inputs @ weights + bias)
loss = (prediction - target) ** 2
print("before : ", round(prediction, 4), "loss : ", round(loss, 4))


d_weighted_sum = 2 * (prediction - target) * (prediction) * (1 - prediction)
weights -= lr * d_weighted_sum * inputs
bias -= lr * d_weighted_sum

prediction = sigmoid(inputs @ weights + bias)
loss = (prediction - target) ** 2
print("after : ", round(prediction, 4), " loss : ", round(loss, 4))
print("Weights now : ", weights.round(3))

before :  0.6457 loss :  0.1256
after :  0.6701  loss :  0.1088
Weights now :  [ 1.041 -0.024]


In [36]:
"""Simple XOR problem solving using MLP"""

from tqdm import tqdm

np.random.seed(0)
inputs = np.array([[0,1], [1,0], [0,0], [1,1]])
targets = np.array([[1], [1], [0], [0]])

def sigmoid(z):
    return 1 / (1 + np.exp(-z))


w_hidden = np.random.randn(2, 4)
b_hidden = np.zeros((1, 4))
w_out = np.random.randn(4, 1)
b_out = np.zeros((1, 1))

print("===========================")
print(w_hidden)
print(b_hidden)
print("===========================")
print(w_out)
print(b_out)
print("===========================")
learning_rate = 1.0

for i in range(1000):
    hidden = sigmoid(inputs @ w_hidden + b_hidden)
    output = sigmoid(hidden @ w_out + b_out)
    loss = np.mean((output - targets) ** 2)

    d_output = 2 * (output - targets) / len(targets) * output * (1 - output)
    d_hidden = (d_output @ w_out.T) * hidden * (1 - hidden)

    w_out -= learning_rate * hidden.T @ d_output
    b_out -= learning_rate * d_output.sum(axis=0, keepdims=True)

    w_hidden -= learning_rate * inputs.T @ d_hidden
    b_hidden -= learning_rate * d_hidden.sum(axis=0, keepdims=True)

    if i % 1000 == 0:
        print("step", step, "loss", round(loss, 4))

print("final predictions:", output.round(3))

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]]
[[0. 0. 0. 0.]]
[[-0.10321885]
 [ 0.4105985 ]
 [ 0.14404357]
 [ 1.45427351]]
[[0.]]
step 599 loss 0.3267
final predictions: [[0.912]
 [0.919]
 [0.084]
 [0.099]]
